# Generated by Django 3.0.8 on 2020-07-23 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('post', '0004_auto_20200721_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=2000)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='caption',
        ),
        migrations.DeleteModel(
            name='CascadeComment',
        ),
        migrations.AddField(
            model_name='childcomment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Comment'),
        ),
    ]
