# Generated by Django 3.0.8 on 2020-08-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='bio',
        ),
        migrations.AddField(
            model_name='bio',
            name='field',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bio',
            name='field_description',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
